# base image
FROM zhuhe0321/mpich:v2.0


# install package here

# e.g. 
# RUN apk add cmake


# current working directory: /app
# compile your project here

# e.g. 
# COPY src/ /app/src/
# RUN cd src/ && make clean && make


# copy the executable file to /app
# file name must be same as the project!

# e.g. 
# RUN cp /app/src/bin/foo /app/PROJ_NAME

CMD ["/bin/ash"]


